#!/usr/bin/env python3
"""Parse the Myss Gallery of Archetypes PDF into structured card data.

Each archetype lives on its own page whose first line is the (lowercase) title.
Family-overview pages start with an uppercase sentence and are skipped as cards,
but the page ranges below define which family each card belongs to.

Outputs src/data/archetypes.ts (a typed array the app imports at build time, so
there is no runtime PDF dependency).
"""
import json
import re
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / "gallery.pdf"
OUT = ROOT / "src" / "data" / "archetypes.ts"

# 1-indexed page ranges -> family (derived from the PDF's family-overview dividers).
FAMILY_RANGES = [
    ("Survival", 5, 16),
    ("Feminine", 17, 23),
    ("Masculine", 24, 31),
    ("Spiritual", 32, 42),
    ("Intellectual", 43, 56),
    ("Helper", 57, 62),
    ("Creative", 63, 76),
    ("Action", 77, 90),
    ("Shadow", 91, 105),
]

# Trailer markers that end the descriptive body of a card page.
TRAILER = re.compile(r"\b(FILMS?|FICTION|RELIGION|MYTH|FAIRY|TAROT|DRAMA|TV)\b")


def family_for(page_num: int) -> str:
    for name, lo, hi in FAMILY_RANGES:
        if lo <= page_num <= hi:
            return name
    return "Other"


SMALL_WORDS = {"of", "and", "or", "the", "a", "an", "to", "in", "for"}


def title_case(text: str) -> str:
    # Capitalize the first letter of every alphabetic run so slash/hyphen
    # compounds like "magician/wizard" -> "Magician/Wizard" read correctly.
    capped = re.sub(
        r"[A-Za-z']+",
        lambda m: m.group(0)[:1].upper() + m.group(0)[1:].lower(),
        text,
    )
    words = capped.split()
    out = []
    for i, w in enumerate(words):
        out.append(w.lower() if i > 0 and w.lower() in SMALL_WORDS else w)
    return " ".join(out)


def clean_name(raw: str) -> str:
    # Drop "(see also ...)" and alternate-name parentheticals, keep the colon form.
    name = raw.split("(")[0].strip()
    name = re.sub(r"\s+", " ", name).rstrip(" ,&")
    if name.lower().startswith("the "):
        name = name[4:]
    # Title-case each segment but preserve the "Family: Subtype" colon structure.
    parts = name.split(":")
    return ": ".join(title_case(p.strip()) for p in parts)


def body_text(page_text: str) -> tuple[str, str]:
    """Return (title_line, joined_body) with the reference trailer removed."""
    lines = page_text.split("\n")
    title = lines[0].strip()
    body_lines = lines[1:]
    body = " ".join(l.strip() for l in body_lines)
    # If the title's parenthetical wrapped onto the next line, the leftover
    # alternate-name fragment ends up at the start of the body. Strip up to the
    # first ")" in that case so it doesn't leak into the blurb.
    if title.count("(") > title.count(")"):
        idx = body.find(")")
        if idx != -1:
            body = body[idx + 1:].lstrip()
    # Cut at the first reference trailer (FILMS/FICTION/...).
    m = TRAILER.search(body)
    if m:
        body = body[: m.start()]
    # De-hyphenate line-break splits and collapse whitespace.
    body = body.replace("- ", "")  # rejoin "self- conscious" style splits
    body = re.sub(r"\s+", " ", body).strip()
    return title, body


def slugify(name: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return s


# Hand-authored light/shadow summaries (tag + short sentence), keyed by id.
ASPECTS = ROOT / "scripts" / "aspects.json"
EMPTY_ASPECT = {"tag": "", "line": ""}


def main() -> None:
    aspects = json.loads(ASPECTS.read_text())
    reader = PdfReader(str(PDF))
    cards = []
    seen = set()
    missing = []
    for i, page in enumerate(reader.pages):
        page_num = i + 1
        if page_num <= 4:  # intro / TOC pages
            continue
        text = (page.extract_text() or "").strip()
        if not text:
            continue
        first = text.split("\n")[0].strip()
        if not first or not first[0].islower():
            continue  # family-overview prose page
        if "(cont" in first.lower():
            continue  # continuation page, body already captured on the prior page
        title, _body = body_text(text)
        name = clean_name(title)
        sid = slugify(name)
        if sid in seen or not name:
            continue
        seen.add(sid)
        aspect = aspects.get(sid)
        if aspect is None:
            missing.append(sid)
            aspect = {"light": EMPTY_ASPECT, "shadow": EMPTY_ASPECT}
        cards.append(
            {
                "id": sid,
                "name": name,
                "family": family_for(page_num),
                "light": aspect["light"],
                "shadow": aspect["shadow"],
            }
        )

    # Emit a typed TS module.
    header = (
        "// AUTO-GENERATED by scripts/extract-archetypes.py from gallery.pdf.\n"
        "// Names/families come from the PDF; light/shadow text from scripts/aspects.json.\n"
        "// Do not edit by hand; re-run `npm run extract` to regenerate.\n"
        "import type { Archetype } from '../types'\n\n"
        "export const ARCHETYPES: Archetype[] = "
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + json.dumps(cards, indent=2, ensure_ascii=False) + "\n")
    print(f"Wrote {len(cards)} archetypes to {OUT.relative_to(ROOT)}")
    extra = [k for k in aspects if k not in seen]
    if missing:
        print(f"  WARNING: {len(missing)} cards missing aspects: {missing}")
    if extra:
        print(f"  WARNING: {len(extra)} aspects with no matching card: {extra}")
    for c in cards[:4]:
        print(f"  - {c['name']}: light={c['light']['tag']!r} / shadow={c['shadow']['tag']!r}")


if __name__ == "__main__":
    main()
