// AUTO-GENERATED by scripts/extract-archetypes.py from gallery.pdf.
// Names/families come from the PDF; light/shadow text from scripts/aspects.json.
// Do not edit by hand; re-run `npm run extract` to regenerate.
import type { Archetype } from '../types'

export const ARCHETYPES: Archetype[] = [
  {
    "id": "child-guardian-of-innocence",
    "name": "Child: Guardian of Innocence",
    "family": "Survival",
    "light": {
      "tag": "Wonder",
      "line": "Meets life with trust, openness, and playful imagination."
    },
    "shadow": {
      "tag": "Dependence",
      "line": "Clings to others instead of growing up and taking responsibility."
    }
  },
  {
    "id": "child-wounded",
    "name": "Child: Wounded",
    "family": "Survival",
    "light": {
      "tag": "Compassion",
      "line": "Turns old wounds into empathy for others who suffer."
    },
    "shadow": {
      "tag": "Self-pity",
      "line": "Nurses grievance and blames the past for present failings."
    }
  },
  {
    "id": "child-orphan-or-abandoned",
    "name": "Child: Orphan or Abandoned",
    "family": "Survival",
    "light": {
      "tag": "Independence",
      "line": "Learns early to build a self apart from the tribe."
    },
    "shadow": {
      "tag": "Abandonment",
      "line": "Never heals the ache of not belonging anywhere."
    }
  },
  {
    "id": "child-magical",
    "name": "Child: Magical",
    "family": "Survival",
    "light": {
      "tag": "Enchantment",
      "line": "Sees sacred possibility and beauty in all things."
    },
    "shadow": {
      "tag": "Disenchantment",
      "line": "Sinks into pessimism when its wonder is wounded."
    }
  },
  {
    "id": "child-divine",
    "name": "Child: Divine",
    "family": "Survival",
    "light": {
      "tag": "Innocence",
      "line": "Carries a redemptive purity and faith in the good."
    },
    "shadow": {
      "tag": "Defenseless",
      "line": "Cannot stand its ground against real harm."
    }
  },
  {
    "id": "child-nature",
    "name": "Child: Nature",
    "family": "Survival",
    "light": {
      "tag": "Kinship",
      "line": "Bonds tenderly with animals and the living world."
    },
    "shadow": {
      "tag": "Cruelty",
      "line": "Turns careless or abusive toward creatures and people."
    }
  },
  {
    "id": "child-eternal",
    "name": "Child: Eternal",
    "family": "Survival",
    "light": {
      "tag": "Youthfulness",
      "line": "Stays forever young in body, mind, and spirit."
    },
    "shadow": {
      "tag": "Peter Pan",
      "line": "Refuses to grow up or carry adult responsibility."
    }
  },
  {
    "id": "child-dependent",
    "name": "Child: Dependent",
    "family": "Survival",
    "light": {
      "tag": "Honest need",
      "line": "Feels its longings openly and seeks to be cared for."
    },
    "shadow": {
      "tag": "Emptiness",
      "line": "Believes nothing is ever enough, and sinks into want."
    }
  },
  {
    "id": "victim",
    "name": "Victim",
    "family": "Survival",
    "light": {
      "tag": "Boundaries",
      "line": "Learns to recognize injustice and protect itself."
    },
    "shadow": {
      "tag": "Blamelessness",
      "line": "Insists that being wronged is never its own doing."
    }
  },
  {
    "id": "prostitute-guardian-of-faith",
    "name": "Prostitute: Guardian of Faith",
    "family": "Survival",
    "light": {
      "tag": "Integrity",
      "line": "Guards its faith and refuses to be bought."
    },
    "shadow": {
      "tag": "Selling out",
      "line": "Trades morals or self for money and safety."
    }
  },
  {
    "id": "saboteur-guardian-of-choice",
    "name": "Saboteur: Guardian of Choice",
    "family": "Survival",
    "light": {
      "tag": "Empowered choice",
      "line": "Spots self-sabotage and chooses to honor its chances."
    },
    "shadow": {
      "tag": "Self-sabotage",
      "line": "Undermines its own success out of low self-worth."
    }
  },
  {
    "id": "queen",
    "name": "Queen",
    "family": "Feminine",
    "light": {
      "tag": "Sovereignty",
      "line": "Wields authority with dignity and benevolence."
    },
    "shadow": {
      "tag": "Tyranny",
      "line": "Turns ruthless when her control is challenged."
    }
  },
  {
    "id": "goddess",
    "name": "Goddess",
    "family": "Feminine",
    "light": {
      "tag": "Life-force",
      "line": "Embodies the creative, regenerative power of the feminine."
    },
    "shadow": {
      "tag": "Vanity",
      "line": "Exploits beauty and allure for indulgence."
    }
  },
  {
    "id": "mother",
    "name": "Mother",
    "family": "Feminine",
    "light": {
      "tag": "Nurture",
      "line": "Gives life, patience, and unconditional protective love."
    },
    "shadow": {
      "tag": "Devouring",
      "line": "Smothers, controls, or abandons those she should nurture."
    }
  },
  {
    "id": "damsel-princess",
    "name": "Damsel & Princess",
    "family": "Feminine",
    "light": {
      "tag": "Grace",
      "line": "Inspires devotion and the promise of care."
    },
    "shadow": {
      "tag": "Helplessness",
      "line": "Plays weak and waits to be rescued."
    }
  },
  {
    "id": "virgin",
    "name": "Virgin",
    "family": "Feminine",
    "light": {
      "tag": "Purity",
      "line": "Holds a sacred, self-possessed innocence."
    },
    "shadow": {
      "tag": "Prudishness",
      "line": "Fears or recoils from genuine sensuality."
    }
  },
  {
    "id": "king",
    "name": "King",
    "family": "Masculine",
    "light": {
      "tag": "Authority",
      "line": "Rules with benevolent power and responsibility."
    },
    "shadow": {
      "tag": "Entitlement",
      "line": "Grows tyrannical and deaf to all challenge."
    }
  },
  {
    "id": "prince",
    "name": "Prince",
    "family": "Masculine",
    "light": {
      "tag": "Promise",
      "line": "Carries the ideals and potential of the heir."
    },
    "shadow": {
      "tag": "Privilege",
      "line": "Exploits his position for self-aggrandizement."
    }
  },
  {
    "id": "father",
    "name": "Father",
    "family": "Masculine",
    "light": {
      "tag": "Protection",
      "line": "Creates, guides, and oversees with steady care."
    },
    "shadow": {
      "tag": "Domination",
      "line": "Turns guidance into dictatorial control."
    }
  },
  {
    "id": "knight-and-warrior",
    "name": "Knight and Warrior",
    "family": "Masculine",
    "light": {
      "tag": "Chivalry",
      "line": "Serves a noble cause with honor and devotion."
    },
    "shadow": {
      "tag": "Black knight",
      "line": "Pledges loyalty to an unworthy ruler or principle."
    }
  },
  {
    "id": "warrior",
    "name": "Warrior",
    "family": "Masculine",
    "light": {
      "tag": "Valor",
      "line": "Stands strong to protect, defend, and fight for what's right."
    },
    "shadow": {
      "tag": "Ruthlessness",
      "line": "Abandons ethics for victory at any cost."
    }
  },
  {
    "id": "lover-don-juan",
    "name": "Lover & Don Juan",
    "family": "Masculine",
    "light": {
      "tag": "Passion",
      "line": "Pours wholehearted devotion into people and pursuits."
    },
    "shadow": {
      "tag": "Obsession",
      "line": "Lets passion curdle into compulsion and conquest."
    }
  },
  {
    "id": "fool-court-jester",
    "name": "Fool/Court Jester",
    "family": "Masculine",
    "light": {
      "tag": "Truth-telling",
      "line": "Speaks hard truths through humor and gets away with it."
    },
    "shadow": {
      "tag": "Betrayal",
      "line": "Twists wit into cruel mockery and broken trust."
    }
  },
  {
    "id": "monk-nun",
    "name": "Monk/Nun",
    "family": "Spiritual",
    "light": {
      "tag": "Devotion",
      "line": "Lives with disciplined spiritual intensity and dedication."
    },
    "shadow": {
      "tag": "Withdrawal",
      "line": "Retreats from the real world into pious isolation."
    }
  },
  {
    "id": "exorcist-shaman",
    "name": "Exorcist & Shaman",
    "family": "Spiritual",
    "light": {
      "tag": "Deliverance",
      "line": "Confronts dark forces to heal and restore."
    },
    "shadow": {
      "tag": "Projection",
      "line": "Attacks the evil in others while dodging his own."
    }
  },
  {
    "id": "priest-priestess",
    "name": "Priest/Priestess",
    "family": "Spiritual",
    "light": {
      "tag": "Sacrament",
      "line": "Channels the sacred and tends the community's faith."
    },
    "shadow": {
      "tag": "Hypocrisy",
      "line": "Breaks the vows it administers, or abuses its office."
    }
  },
  {
    "id": "disciple",
    "name": "Disciple",
    "family": "Spiritual",
    "light": {
      "tag": "Devotion",
      "line": "Commits wholeheartedly to a teacher and a path."
    },
    "shadow": {
      "tag": "Blind faith",
      "line": "Forsakes reason under another's spell."
    }
  },
  {
    "id": "martyr",
    "name": "Martyr",
    "family": "Spiritual",
    "light": {
      "tag": "Sacrifice",
      "line": "Has the courage to suffer for a worthy cause."
    },
    "shadow": {
      "tag": "Suffering for control",
      "line": "Uses service and suffering to manipulate others."
    }
  },
  {
    "id": "samaritan",
    "name": "Samaritan",
    "family": "Spiritual",
    "light": {
      "tag": "Grace",
      "line": "Helps the stranger with selfless, sacred care."
    },
    "shadow": {
      "tag": "Selective mercy",
      "line": "Aids some at others' expense, with quiet self-importance."
    }
  },
  {
    "id": "missionary",
    "name": "Missionary",
    "family": "Spiritual",
    "light": {
      "tag": "Calling",
      "line": "Devotes itself to carrying help and faith where it's needed."
    },
    "shadow": {
      "tag": "Imposition",
      "line": "Forces its beliefs on others in the name of care."
    }
  },
  {
    "id": "angel",
    "name": "Angel",
    "family": "Spiritual",
    "light": {
      "tag": "Messenger",
      "line": "Brings light, guidance, and protection to others."
    },
    "shadow": {
      "tag": "False light",
      "line": "Feigns innocence to mislead, or claims guidance for ego."
    }
  },
  {
    "id": "god",
    "name": "God",
    "family": "Spiritual",
    "light": {
      "tag": "Benevolence",
      "line": "Uses great power compassionately for humanity."
    },
    "shadow": {
      "tag": "Despotism",
      "line": "Becomes a dictator who takes without giving back."
    }
  },
  {
    "id": "messiah",
    "name": "Messiah",
    "family": "Spiritual",
    "light": {
      "tag": "Redemption",
      "line": "Answers a true calling to serve and save."
    },
    "shadow": {
      "tag": "Savior delusion",
      "line": "Mistakes ego for mission, like a cult leader."
    }
  },
  {
    "id": "mystic",
    "name": "Mystic",
    "family": "Intellectual",
    "light": {
      "tag": "Union",
      "line": "Walks the hard path toward direct experience of the divine."
    },
    "shadow": {
      "tag": "Spiritual ego",
      "line": "Craves higher states and status above others."
    }
  },
  {
    "id": "teacher",
    "name": "Teacher",
    "family": "Intellectual",
    "light": {
      "tag": "Imparting",
      "line": "Communicates knowledge, skill, and wisdom to others."
    },
    "shadow": {
      "tag": "Manipulation",
      "line": "Exploits students or teaches destructive ends."
    }
  },
  {
    "id": "student",
    "name": "Student",
    "family": "Intellectual",
    "light": {
      "tag": "Curiosity",
      "line": "Stays endlessly open to learning and growth."
    },
    "shadow": {
      "tag": "Eternal student",
      "line": "Hides in study, never mastering or living fully."
    }
  },
  {
    "id": "guide",
    "name": "Guide",
    "family": "Intellectual",
    "light": {
      "tag": "Spiritual guidance",
      "line": "Helps others see the divine in everyday life."
    },
    "shadow": {
      "tag": "False guru",
      "line": "Seeks money and control over genuine insight."
    }
  },
  {
    "id": "mentor",
    "name": "Mentor",
    "family": "Intellectual",
    "light": {
      "tag": "Trust",
      "line": "Offers wisdom and trusted counsel to a protégé."
    },
    "shadow": {
      "tag": "Control",
      "line": "Refuses to let the student surpass and move on."
    }
  },
  {
    "id": "philosopher",
    "name": "Philosopher",
    "family": "Intellectual",
    "light": {
      "tag": "Wisdom",
      "line": "Loves thought and seeks transcendent meaning."
    },
    "shadow": {
      "tag": "Despair",
      "line": "Sinks into the doomsayer for whom life has no meaning."
    }
  },
  {
    "id": "sage-and-crone",
    "name": "Sage and Crone",
    "family": "Intellectual",
    "light": {
      "tag": "Wise counsel",
      "line": "Passes hard-won knowledge on to others."
    },
    "shadow": {
      "tag": "Hidden agenda",
      "line": "Colors its wisdom with personal fears and motives."
    }
  },
  {
    "id": "seeker-and-wanderer",
    "name": "Seeker and Wanderer",
    "family": "Intellectual",
    "light": {
      "tag": "Quest",
      "line": "Journeys lifelong in pursuit of truth and meaning."
    },
    "shadow": {
      "tag": "Lost soul",
      "line": "Wanders aimlessly, ungrounded and disconnected."
    }
  },
  {
    "id": "hermit",
    "name": "Hermit",
    "family": "Intellectual",
    "light": {
      "tag": "Solitude",
      "line": "Withdraws to find renewal and inner depth."
    },
    "shadow": {
      "tag": "Isolation",
      "line": "Never wants to be around anyone at all."
    }
  },
  {
    "id": "alchemist",
    "name": "Alchemist",
    "family": "Intellectual",
    "light": {
      "tag": "Transformation",
      "line": "Seeks genuine spiritual and material transmutation."
    },
    "shadow": {
      "tag": "Dark arts",
      "line": "Misuses power and knowledge for selfish ends."
    }
  },
  {
    "id": "storyteller",
    "name": "Storyteller",
    "family": "Intellectual",
    "light": {
      "tag": "Myth-making",
      "line": "Carries wisdom and delight through larger-than-life tales."
    },
    "shadow": {
      "tag": "Deception",
      "line": "Exaggerates or lies to conceal the truth."
    }
  },
  {
    "id": "judge",
    "name": "Judge",
    "family": "Intellectual",
    "light": {
      "tag": "Discernment",
      "line": "Weighs fairly, with wisdom and compassion."
    },
    "shadow": {
      "tag": "Condemnation",
      "line": "Criticizes without mercy or with a hidden agenda."
    }
  },
  {
    "id": "mediator",
    "name": "Mediator",
    "family": "Intellectual",
    "light": {
      "tag": "Reconciliation",
      "line": "Bridges opposing sides with patience and fairness."
    },
    "shadow": {
      "tag": "Double-dealing",
      "line": "Works both sides for personal gain."
    }
  },
  {
    "id": "healer-wounded-healer",
    "name": "Healer/Wounded Healer",
    "family": "Helper",
    "light": {
      "tag": "Restoration",
      "line": "Serves to repair body, mind, and spirit."
    },
    "shadow": {
      "tag": "False healer",
      "line": "Preys on the vulnerable with empty promises."
    }
  },
  {
    "id": "rescuer",
    "name": "Rescuer",
    "family": "Helper",
    "light": {
      "tag": "Aid",
      "line": "Lends strength in a crisis, then steps back."
    },
    "shadow": {
      "tag": "Codependence",
      "line": "Rescues to bind others through a hidden need."
    }
  },
  {
    "id": "servant-indentured-servant",
    "name": "Servant/Indentured Servant",
    "family": "Helper",
    "light": {
      "tag": "Service",
      "line": "Gives itself freely to others and to spirit."
    },
    "shadow": {
      "tag": "Indenture",
      "line": "Postpones its own life, in bondage to obligation."
    }
  },
  {
    "id": "caretaker",
    "name": "Caretaker",
    "family": "Helper",
    "light": {
      "tag": "Caregiving",
      "line": "Tends others as naturally as breathing."
    },
    "shadow": {
      "tag": "Burnout",
      "line": "Loses itself and resents the endless giving."
    }
  },
  {
    "id": "companion",
    "name": "Companion",
    "family": "Helper",
    "light": {
      "tag": "Loyalty",
      "line": "Offers steadfast friendship and support to another."
    },
    "shadow": {
      "tag": "Betrayal",
      "line": "Betrays trust, or clings on without real chemistry."
    }
  },
  {
    "id": "artist",
    "name": "Artist",
    "family": "Creative",
    "light": {
      "tag": "Expression",
      "line": "Channels the unseen into living form."
    },
    "shadow": {
      "tag": "Tortured genius",
      "line": "Suppresses its gift through fear and self-destruction."
    }
  },
  {
    "id": "scribe",
    "name": "Scribe",
    "family": "Creative",
    "light": {
      "tag": "Preservation",
      "line": "Faithfully records and keeps knowledge alive."
    },
    "shadow": {
      "tag": "Falsification",
      "line": "Alters facts, plagiarizes, or sells what isn't his."
    }
  },
  {
    "id": "pioneer-and-explorer",
    "name": "Pioneer and Explorer",
    "family": "Creative",
    "light": {
      "tag": "Discovery",
      "line": "Strikes out to explore new outer and inner lands."
    },
    "shadow": {
      "tag": "Restlessness",
      "line": "Compulsively abandons the past for the next frontier."
    }
  },
  {
    "id": "statesman-and-politician",
    "name": "Statesman and Politician",
    "family": "Creative",
    "light": {
      "tag": "Statecraft",
      "line": "Brings dignity and vision to public service."
    },
    "shadow": {
      "tag": "The politician",
      "line": "Trades honesty for expediency and self-interest."
    }
  },
  {
    "id": "strategist",
    "name": "Strategist",
    "family": "Creative",
    "light": {
      "tag": "Cleverness",
      "line": "Plans skillfully to turn vision into results."
    },
    "shadow": {
      "tag": "Scheming",
      "line": "Uses control and cunning to get its way."
    }
  },
  {
    "id": "networker",
    "name": "Networker",
    "family": "Creative",
    "light": {
      "tag": "Connection",
      "line": "Forges alliances across very different worlds."
    },
    "shadow": {
      "tag": "Using people",
      "line": "Exploits connections purely for personal gain."
    }
  },
  {
    "id": "gossip",
    "name": "Gossip",
    "family": "Creative",
    "light": {
      "tag": "Common talk",
      "line": "Carries the everyday news that binds a community."
    },
    "shadow": {
      "tag": "Slander",
      "line": "Spreads harmful, disempowering rumors for power."
    }
  },
  {
    "id": "entrepreneur-and-philanthropist",
    "name": "Entrepreneur and Philanthropist",
    "family": "Creative",
    "light": {
      "tag": "Enterprise",
      "line": "Brings creative vision and generosity to business."
    },
    "shadow": {
      "tag": "Self-interest",
      "line": "Bends giving and abundance toward personal gain."
    }
  },
  {
    "id": "athlete-olympian",
    "name": "Athlete/Olympian",
    "family": "Creative",
    "light": {
      "tag": "Prowess",
      "line": "Expresses the strength and grace of the human body."
    },
    "shadow": {
      "tag": "Invincibility",
      "line": "Misuses its strength and believes itself untouchable."
    }
  },
  {
    "id": "visionary-and-prophet",
    "name": "Visionary and Prophet",
    "family": "Creative",
    "light": {
      "tag": "Foresight",
      "line": "Imagines possibilities that benefit all of society."
    },
    "shadow": {
      "tag": "Sellout",
      "line": "Sells or softens its vision to be accepted."
    }
  },
  {
    "id": "poet",
    "name": "Poet",
    "family": "Creative",
    "light": {
      "tag": "Lyricism",
      "line": "Finds beauty and truth in great and small things."
    },
    "shadow": {
      "tag": "Corrupted voice",
      "line": "Bends its gift to destructive or hateful ends."
    }
  },
  {
    "id": "dilettante",
    "name": "Dilettante",
    "family": "Creative",
    "light": {
      "tag": "Delight",
      "line": "Loves the arts with genuine, playful enthusiasm."
    },
    "shadow": {
      "tag": "Pretension",
      "line": "Pretends to far deeper knowledge than it has."
    }
  },
  {
    "id": "engineer",
    "name": "Engineer",
    "family": "Creative",
    "light": {
      "tag": "Ingenuity",
      "line": "Turns creative energy into things that work."
    },
    "shadow": {
      "tag": "Manipulation",
      "line": "Engineers situations to its own advantage."
    }
  },
  {
    "id": "hero-heroine",
    "name": "Hero/Heroine",
    "family": "Action",
    "light": {
      "tag": "Courage",
      "line": "Faces hard trials to grow and protect others."
    },
    "shadow": {
      "tag": "Self-glory",
      "line": "Seeks empowerment by disempowering others."
    }
  },
  {
    "id": "bully-and-coward",
    "name": "Bully and Coward",
    "family": "Action",
    "light": {
      "tag": "Inner strength",
      "line": "Learns that spirit is stronger than fear."
    },
    "shadow": {
      "tag": "Intimidation",
      "line": "Bullies the weak and cowers before the strong."
    }
  },
  {
    "id": "mercenary",
    "name": "Mercenary",
    "family": "Action",
    "light": {
      "tag": "Hired skill",
      "line": "Delivers results with disciplined, dispassionate focus."
    },
    "shadow": {
      "tag": "No heart",
      "line": "Sells its skills with no conscience or loyalty."
    }
  },
  {
    "id": "gambler",
    "name": "Gambler",
    "family": "Action",
    "light": {
      "tag": "Risk-taking",
      "line": "Plays the odds, trusting instinct and luck."
    },
    "shadow": {
      "tag": "Compulsion",
      "line": "Cannot stop chasing the bet, addicted to risk."
    }
  },
  {
    "id": "rebel",
    "name": "Rebel",
    "family": "Action",
    "light": {
      "tag": "Revolution",
      "line": "Breaks stale conventions to free what's possible."
    },
    "shadow": {
      "tag": "Contrarian",
      "line": "Rebels for fashion or to dodge legitimate demands."
    }
  },
  {
    "id": "destroyer",
    "name": "Destroyer",
    "family": "Action",
    "light": {
      "tag": "Renewal",
      "line": "Tears down the old so new life can be born."
    },
    "shadow": {
      "tag": "Annihilation",
      "line": "Destroys for its own sake, drunk on the power."
    }
  },
  {
    "id": "detective",
    "name": "Detective",
    "family": "Action",
    "light": {
      "tag": "Investigation",
      "line": "Uncovers hidden truth to protect the public."
    },
    "shadow": {
      "tag": "Surveillance",
      "line": "Slides into voyeurism, spying, and falsified facts."
    }
  },
  {
    "id": "midas-and-miser",
    "name": "Midas and Miser",
    "family": "Action",
    "light": {
      "tag": "Prosperity",
      "line": "Holds the golden touch that creates wealth."
    },
    "shadow": {
      "tag": "Hoarding",
      "line": "Hoards money and feeling at everyone's expense."
    }
  },
  {
    "id": "slave",
    "name": "Slave",
    "family": "Action",
    "light": {
      "tag": "Surrender",
      "line": "Masters the self by releasing the illusion of control."
    },
    "shadow": {
      "tag": "Bondage",
      "line": "Falls enslaved to a substance, person, or society."
    }
  },
  {
    "id": "liberator",
    "name": "Liberator",
    "family": "Action",
    "light": {
      "tag": "Freedom",
      "line": "Frees others from servitude and oppression."
    },
    "shadow": {
      "tag": "New tyranny",
      "line": "Frees from one tyrant only to impose its own."
    }
  },
  {
    "id": "advocate",
    "name": "Advocate",
    "family": "Action",
    "light": {
      "tag": "Championing",
      "line": "Devotes itself to the rights of others in public."
    },
    "shadow": {
      "tag": "False cause",
      "line": "Champions causes for personal gain or harm."
    }
  },
  {
    "id": "avenger",
    "name": "Avenger",
    "family": "Action",
    "light": {
      "tag": "Justice",
      "line": "Works to balance the scales for the wronged."
    },
    "shadow": {
      "tag": "Vengeance",
      "line": "Avenges through violence and zealotry."
    }
  },
  {
    "id": "housewife-and-working-mother",
    "name": "Housewife and Working Mother",
    "family": "Action",
    "light": {
      "tag": "Home-making",
      "line": "Holds the household and family together with devotion."
    },
    "shadow": {
      "tag": "Negligence",
      "line": "The absent mother who never truly comes home."
    }
  },
  {
    "id": "addict",
    "name": "Addict",
    "family": "Shadow",
    "light": {
      "tag": "Surrender",
      "line": "Admitting powerlessness can open a path to freedom."
    },
    "shadow": {
      "tag": "Compulsion",
      "line": "Surrenders will and self-control to a craving."
    }
  },
  {
    "id": "holy-fool",
    "name": "Holy Fool",
    "family": "Shadow",
    "light": {
      "tag": "Sacred wit",
      "line": "Speaks truth through folly and gets away with it."
    },
    "shadow": {
      "tag": "Self-betrayal",
      "line": "Acts against its own wisdom and plays the real fool."
    }
  },
  {
    "id": "trickster",
    "name": "Trickster",
    "family": "Shadow",
    "light": {
      "tag": "Cunning play",
      "line": "Upends the rules with clever, transformative mischief."
    },
    "shadow": {
      "tag": "Endless tricks",
      "line": "Cannot stop deceiving, driven by restless energy."
    }
  },
  {
    "id": "provocateur",
    "name": "Provocateur",
    "family": "Shadow",
    "light": {
      "tag": "Provocation",
      "line": "Stirs people awake with bold, catalyzing energy."
    },
    "shadow": {
      "tag": "Seduction",
      "line": "Plays seductive games to manipulate and con."
    }
  },
  {
    "id": "spellcaster",
    "name": "Spellcaster",
    "family": "Shadow",
    "light": {
      "tag": "Influence",
      "line": "Shapes reality through focused intention and will."
    },
    "shadow": {
      "tag": "Dark spells",
      "line": "Bends others' will for selfish or harmful ends."
    }
  },
  {
    "id": "magician-wizard",
    "name": "Magician/Wizard",
    "family": "Shadow",
    "light": {
      "tag": "Mastery",
      "line": "Produces real results beyond the ordinary rules."
    },
    "shadow": {
      "tag": "Misused power",
      "line": "Turns ingenuity to criminal or unethical ends."
    }
  },
  {
    "id": "hedonist",
    "name": "Hedonist",
    "family": "Shadow",
    "light": {
      "tag": "Pleasure",
      "line": "Savors life's delights as part of a balanced life."
    },
    "shadow": {
      "tag": "Excess",
      "line": "Chases pleasure heedless of others or health."
    }
  },
  {
    "id": "vampire",
    "name": "Vampire",
    "family": "Shadow",
    "light": {
      "tag": "Magnetism",
      "line": "Holds a seductive, irresistible allure."
    },
    "shadow": {
      "tag": "Draining",
      "line": "Feeds on others' vitality to fill its own emptiness."
    }
  },
  {
    "id": "shape-shifter",
    "name": "Shape-Shifter",
    "family": "Shadow",
    "light": {
      "tag": "Adaptability",
      "line": "Moves fluidly between roles and states of being."
    },
    "shadow": {
      "tag": "Instability",
      "line": "Reinvents itself with no conviction or core."
    }
  },
  {
    "id": "femme-fatale",
    "name": "Femme Fatale",
    "family": "Shadow",
    "light": {
      "tag": "Allure",
      "line": "Owns the full power of feminine magnetism."
    },
    "shadow": {
      "tag": "Manipulation",
      "line": "Uses seduction to control and undo others."
    }
  },
  {
    "id": "thief",
    "name": "Thief",
    "family": "Shadow",
    "light": {
      "tag": "Resourcefulness",
      "line": "Has the daring and skill to seize the unreachable."
    },
    "shadow": {
      "tag": "Stealing",
      "line": "Takes what belongs to others by stealth."
    }
  },
  {
    "id": "pirate",
    "name": "Pirate",
    "family": "Shadow",
    "light": {
      "tag": "Freedom",
      "line": "Lives by its own rules, a symbol of untamed liberty."
    },
    "shadow": {
      "tag": "Plunder",
      "line": "Seizes others' treasure as a lawless bandit."
    }
  },
  {
    "id": "clown",
    "name": "Clown",
    "family": "Shadow",
    "light": {
      "tag": "Mirth",
      "line": "Makes others laugh and cry from behind the mask."
    },
    "shadow": {
      "tag": "Masked malice",
      "line": "Hides cruelty behind the painted smile."
    }
  },
  {
    "id": "beggar",
    "name": "Beggar",
    "family": "Shadow",
    "light": {
      "tag": "Humility",
      "line": "Teaches compassion, dependence, and the dignity within need."
    },
    "shadow": {
      "tag": "Destitution",
      "line": "Lives stripped of all resources, at others' mercy."
    }
  }
]
